/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaitlistRouteImport } from './routes/waitlist'
import { Route as SavingsRouteImport } from './routes/savings'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OurStoryRouteImport } from './routes/our-story'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LunchesRouteImport } from './routes/lunches'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MealIdRouteImport } from './routes/meal.$id'

const WaitlistRoute = WaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const SavingsRoute = SavingsRouteImport.update({
  id: '/savings',
  path: '/savings',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OurStoryRoute = OurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LunchesRoute = LunchesRouteImport.update({
  id: '/lunches',
  path: '/lunches',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MealIdRoute = MealIdRouteImport.update({
  id: '/meal/$id',
  path: '/meal/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/faq': typeof FaqRoute
  '/history': typeof HistoryRoute
  '/lunches': typeof LunchesRoute
  '/onboarding': typeof OnboardingRoute
  '/our-story': typeof OurStoryRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/savings': typeof SavingsRoute
  '/waitlist': typeof WaitlistRoute
  '/meal/$id': typeof MealIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/faq': typeof FaqRoute
  '/history': typeof HistoryRoute
  '/lunches': typeof LunchesRoute
  '/onboarding': typeof OnboardingRoute
  '/our-story': typeof OurStoryRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/savings': typeof SavingsRoute
  '/waitlist': typeof WaitlistRoute
  '/meal/$id': typeof MealIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/faq': typeof FaqRoute
  '/history': typeof HistoryRoute
  '/lunches': typeof LunchesRoute
  '/onboarding': typeof OnboardingRoute
  '/our-story': typeof OurStoryRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/savings': typeof SavingsRoute
  '/waitlist': typeof WaitlistRoute
  '/meal/$id': typeof MealIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/faq'
    | '/history'
    | '/lunches'
    | '/onboarding'
    | '/our-story'
    | '/profile'
    | '/saved'
    | '/savings'
    | '/waitlist'
    | '/meal/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/faq'
    | '/history'
    | '/lunches'
    | '/onboarding'
    | '/our-story'
    | '/profile'
    | '/saved'
    | '/savings'
    | '/waitlist'
    | '/meal/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/faq'
    | '/history'
    | '/lunches'
    | '/onboarding'
    | '/our-story'
    | '/profile'
    | '/saved'
    | '/savings'
    | '/waitlist'
    | '/meal/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  FaqRoute: typeof FaqRoute
  HistoryRoute: typeof HistoryRoute
  LunchesRoute: typeof LunchesRoute
  OnboardingRoute: typeof OnboardingRoute
  OurStoryRoute: typeof OurStoryRoute
  ProfileRoute: typeof ProfileRoute
  SavedRoute: typeof SavedRoute
  SavingsRoute: typeof SavingsRoute
  WaitlistRoute: typeof WaitlistRoute
  MealIdRoute: typeof MealIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waitlist': {
      id: '/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof WaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/savings': {
      id: '/savings'
      path: '/savings'
      fullPath: '/savings'
      preLoaderRoute: typeof SavingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-story': {
      id: '/our-story'
      path: '/our-story'
      fullPath: '/our-story'
      preLoaderRoute: typeof OurStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lunches': {
      id: '/lunches'
      path: '/lunches'
      fullPath: '/lunches'
      preLoaderRoute: typeof LunchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meal/$id': {
      id: '/meal/$id'
      path: '/meal/$id'
      fullPath: '/meal/$id'
      preLoaderRoute: typeof MealIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  FaqRoute: FaqRoute,
  HistoryRoute: HistoryRoute,
  LunchesRoute: LunchesRoute,
  OnboardingRoute: OnboardingRoute,
  OurStoryRoute: OurStoryRoute,
  ProfileRoute: ProfileRoute,
  SavedRoute: SavedRoute,
  SavingsRoute: SavingsRoute,
  WaitlistRoute: WaitlistRoute,
  MealIdRoute: MealIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
